"""baseline esquema inicial

Revision ID: fefcd5a0b14a
Revises: 
Create Date: 2026-06-13 10:10:49.764466
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# identificadores de revisión, usados por Alembic.
revision: str = 'fefcd5a0b14a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('songs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('artist', sa.String(length=255), nullable=True),
    sa.Column('album', sa.String(length=255), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('bpm', sa.Integer(), nullable=True),
    sa.Column('time_signature_num', sa.Integer(), nullable=True),
    sa.Column('time_signature_den', sa.Integer(), nullable=True),
    sa.Column('key_root', sa.String(length=4), nullable=True),
    sa.Column('key_mode', sa.String(length=32), nullable=True),
    sa.Column('tuning', sa.String(length=32), nullable=True),
    sa.Column('capo', sa.Integer(), nullable=True),
    sa.Column('instrument', sa.String(length=32), nullable=True),
    sa.Column('format_version', sa.String(length=8), nullable=True),
    sa.Column('owner_id', sa.String(length=36), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('source_type', sa.String(length=32), nullable=True),
    sa.Column('source_file_path', sa.Text(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('duration_beats', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('songs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_songs_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_songs_owner_id'), ['owner_id'], unique=False)

    op.create_table('sections',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('song_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('repeat_count', sa.Integer(), nullable=True),
    sa.Column('color_tag', sa.String(length=7), nullable=True),
    sa.ForeignKeyConstraint(['song_id'], ['songs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sections_song_id'), ['song_id'], unique=False)

    op.create_table('lines',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('section_id', sa.String(length=36), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('beat_start', sa.Float(), nullable=True),
    sa.Column('beat_duration', sa.Float(), nullable=True),
    sa.Column('display_hint', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lines_section_id'), ['section_id'], unique=False)

    op.create_table('chord_markers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('line_id', sa.String(length=36), nullable=False),
    sa.Column('chord_name', sa.String(length=16), nullable=False),
    sa.Column('char_position', sa.Integer(), nullable=True),
    sa.Column('beat_offset', sa.Float(), nullable=True),
    sa.Column('duration_beats', sa.Float(), nullable=True),
    sa.Column('finger_diagram', sa.JSON(), nullable=True),
    sa.Column('barre', sa.JSON(), nullable=True),
    sa.Column('muted_strings', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['line_id'], ['lines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chord_markers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chord_markers_line_id'), ['line_id'], unique=False)

    op.create_table('tab_lines',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('line_id', sa.String(length=36), nullable=False),
    sa.Column('string_number', sa.Integer(), nullable=False),
    sa.Column('fret_sequence', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['line_id'], ['lines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tab_lines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tab_lines_line_id'), ['line_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tab_lines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tab_lines_line_id'))

    op.drop_table('tab_lines')
    with op.batch_alter_table('chord_markers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chord_markers_line_id'))

    op.drop_table('chord_markers')
    with op.batch_alter_table('lines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lines_section_id'))

    op.drop_table('lines')
    with op.batch_alter_table('sections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sections_song_id'))

    op.drop_table('sections')
    with op.batch_alter_table('songs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_songs_owner_id'))
        batch_op.drop_index(batch_op.f('ix_songs_deleted_at'))

    op.drop_table('songs')
    # ### end Alembic commands ###
