"""Song.band_id repertorio de banda T-057

Revision ID: 908a0a3875b1
Revises: 39fbdc0fff0f
Create Date: 2026-06-16 04:21:36.724389
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# identificadores de revisión, usados por Alembic.
revision: str = '908a0a3875b1'
down_revision: Union[str, None] = '39fbdc0fff0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('songs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('band_id', sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f('ix_songs_band_id'), ['band_id'], unique=False)
        batch_op.create_foreign_key(
            'fk_songs_band_id_bands', 'bands', ['band_id'], ['id'], ondelete='CASCADE'
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('songs', schema=None) as batch_op:
        batch_op.drop_constraint('fk_songs_band_id_bands', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_songs_band_id'))
        batch_op.drop_column('band_id')

    # ### end Alembic commands ###
