"""Agenda eventos + asistencia Fase 10 T-063

Revision ID: 22c7ea96b921
Revises: 95eddae092db
Create Date: 2026-06-16 05:36:48.847901
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# identificadores de revisión, usados por Alembic.
revision: str = '22c7ea96b921'
down_revision: Union[str, None] = '95eddae092db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('band_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('starts_at', sa.DateTime(), nullable=True),
    sa.Column('ends_at', sa.DateTime(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), server_default=sa.text("'confirmed'"), nullable=False),
    sa.Column('setlist_id', sa.String(length=36), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("status IN ('lead', 'contacted', 'negotiating', 'confirmed', 'done', 'cancelled')", name='ck_events_status'),
    sa.CheckConstraint("type IN ('rehearsal', 'concert', 'other')", name='ck_events_type'),
    sa.ForeignKeyConstraint(['band_id'], ['bands.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['setlist_id'], ['setlists.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_events_band_id'), ['band_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_deleted_at'), ['deleted_at'], unique=False)

    op.create_table('event_attendance',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('event_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=8), nullable=False),
    sa.Column('responded_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("status IN ('yes', 'no', 'maybe')", name='ck_attendance_status'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'user_id', name='uq_attendance_event_user')
    )
    with op.batch_alter_table('event_attendance', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_attendance_event_id'), ['event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_attendance_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_attendance', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_attendance_user_id'))
        batch_op.drop_index(batch_op.f('ix_event_attendance_event_id'))

    op.drop_table('event_attendance')
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_events_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_events_band_id'))

    op.drop_table('events')
    # ### end Alembic commands ###
