"""Setlist.band_id + SetlistItem.note Fase 9 T-060

Revision ID: 95eddae092db
Revises: 908a0a3875b1
Create Date: 2026-06-16 05:13:43.012718
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# identificadores de revisión, usados por Alembic.
revision: str = '95eddae092db'
down_revision: Union[str, None] = '908a0a3875b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('setlist_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('note', sa.Text(), nullable=True))

    with op.batch_alter_table('setlists', schema=None) as batch_op:
        batch_op.add_column(sa.Column('band_id', sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f('ix_setlists_band_id'), ['band_id'], unique=False)
        batch_op.create_foreign_key(
            'fk_setlists_band_id_bands', 'bands', ['band_id'], ['id'], ondelete='CASCADE'
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('setlists', schema=None) as batch_op:
        batch_op.drop_constraint('fk_setlists_band_id_bands', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_setlists_band_id'))
        batch_op.drop_column('band_id')

    with op.batch_alter_table('setlist_items', schema=None) as batch_op:
        batch_op.drop_column('note')

    # ### end Alembic commands ###
