"""Finanzas Transaction Split Settlement + Band.currency Fase 11 T-066

Revision ID: 84c9ca4f7b64
Revises: 22c7ea96b921
Create Date: 2026-06-16 06:00:54.113336
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# identificadores de revisión, usados por Alembic.
revision: str = '84c9ca4f7b64'
down_revision: Union[str, None] = '22c7ea96b921'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settlements',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('band_id', sa.String(length=36), nullable=False),
    sa.Column('from_user_id', sa.String(length=36), nullable=False),
    sa.Column('to_user_id', sa.String(length=36), nullable=True),
    sa.Column('to_fund', sa.Boolean(), server_default=sa.text('(false)'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['band_id'], ['bands.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('settlements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_settlements_band_id'), ['band_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_settlements_deleted_at'), ['deleted_at'], unique=False)

    op.create_table('transactions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('band_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.String(length=8), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('paid_by', sa.String(length=36), nullable=True),
    sa.Column('paid_by_fund', sa.Boolean(), server_default=sa.text('(false)'), nullable=False),
    sa.Column('event_id', sa.String(length=36), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("type IN ('expense', 'income')", name='ck_transactions_type'),
    sa.ForeignKeyConstraint(['band_id'], ['bands.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transactions_band_id'), ['band_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_deleted_at'), ['deleted_at'], unique=False)

    op.create_table('transaction_splits',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('transaction_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('share_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('to_fund', sa.Boolean(), server_default=sa.text('(false)'), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transaction_splits', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transaction_splits_transaction_id'), ['transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transaction_splits_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('bands', schema=None) as batch_op:
        batch_op.add_column(sa.Column('currency', sa.String(length=3), server_default=sa.text("'EUR'"), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bands', schema=None) as batch_op:
        batch_op.drop_column('currency')

    with op.batch_alter_table('transaction_splits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transaction_splits_user_id'))
        batch_op.drop_index(batch_op.f('ix_transaction_splits_transaction_id'))

    op.drop_table('transaction_splits')
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transactions_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_transactions_band_id'))

    op.drop_table('transactions')
    with op.batch_alter_table('settlements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_settlements_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_settlements_band_id'))

    op.drop_table('settlements')
    # ### end Alembic commands ###
