"""venues + events.venue_id (T-116)

Revision ID: 91d60406fb92
Revises: c341c9bbb0ba
Create Date: 2026-06-21 06:13:25.088546
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# identificadores de revisión, usados por Alembic.
revision: str = '91d60406fb92'
down_revision: Union[str, None] = 'c341c9bbb0ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('venues',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('band_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.String(length=512), nullable=True),
    sa.Column('city', sa.String(length=255), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('contact', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['band_id'], ['bands.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('venues', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_venues_band_id'), ['band_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_venues_deleted_at'), ['deleted_at'], unique=False)

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('venue_id', sa.String(length=36), nullable=True))
        batch_op.create_foreign_key('fk_events_venue_id_venues', 'venues',
                                    ['venue_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_constraint('fk_events_venue_id_venues', type_='foreignkey')
        batch_op.drop_column('venue_id')

    with op.batch_alter_table('venues', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_venues_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_venues_band_id'))

    op.drop_table('venues')
    # ### end Alembic commands ###
