"""core de banda (identidad) T-048

Revision ID: 39fbdc0fff0f
Revises: 3684ab6335e8
Create Date: 2026-06-15 19:27:18.073878
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# identificadores de revisión, usados por Alembic.
revision: str = '39fbdc0fff0f'
down_revision: Union[str, None] = '3684ab6335e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bands',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('avatar_url', sa.String(length=512), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bands', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bands_created_by'), ['created_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_bands_deleted_at'), ['deleted_at'], unique=False)

    op.create_table('musician_profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('instruments', sa.JSON(), nullable=True),
    sa.Column('avatar_url', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('band_invites',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('band_id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('role_to_grant', sa.String(length=16), server_default=sa.text("'member'"), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('max_uses', sa.Integer(), nullable=True),
    sa.Column('used_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("role_to_grant IN ('admin', 'member', 'guest')", name='ck_invite_role'),
    sa.ForeignKeyConstraint(['band_id'], ['bands.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('band_invites', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_band_invites_band_id'), ['band_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_band_invites_code'), ['code'], unique=True)

    op.create_table('band_memberships',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('band_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=16), server_default=sa.text("'member'"), nullable=False),
    sa.Column('instrument', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=16), server_default=sa.text("'active'"), nullable=False),
    sa.Column('left_at', sa.DateTime(), nullable=True),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("role IN ('admin', 'member', 'guest')", name='ck_membership_role'),
    sa.CheckConstraint("status IN ('active', 'left')", name='ck_membership_status'),
    sa.ForeignKeyConstraint(['band_id'], ['bands.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('band_id', 'user_id', name='uq_membership_band_user')
    )
    with op.batch_alter_table('band_memberships', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_band_memberships_band_id'), ['band_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_band_memberships_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('band_memberships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_band_memberships_user_id'))
        batch_op.drop_index(batch_op.f('ix_band_memberships_band_id'))

    op.drop_table('band_memberships')
    with op.batch_alter_table('band_invites', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_band_invites_code'))
        batch_op.drop_index(batch_op.f('ix_band_invites_band_id'))

    op.drop_table('band_invites')
    op.drop_table('musician_profiles')
    with op.batch_alter_table('bands', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bands_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_bands_created_by'))

    op.drop_table('bands')
    # ### end Alembic commands ###
