"""song_collections + items (T-114 repertorios)

Revision ID: 5481a965f5fb
Revises: e9f1a2b3c4d5
Create Date: 2026-06-21 04:50:28.240413
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# identificadores de revisión, usados por Alembic.
revision: str = '5481a965f5fb'
down_revision: Union[str, None] = 'e9f1a2b3c4d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('song_collections',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('band_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['band_id'], ['bands.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('song_collections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_song_collections_band_id'), ['band_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_song_collections_deleted_at'), ['deleted_at'], unique=False)

    op.create_table('song_collection_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('collection_id', sa.String(length=36), nullable=False),
    sa.Column('song_id', sa.String(length=36), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['song_collections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['song_id'], ['songs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('collection_id', 'song_id', name='uq_collection_song')
    )
    with op.batch_alter_table('song_collection_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_song_collection_items_collection_id'), ['collection_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_song_collection_items_song_id'), ['song_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('song_collection_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_song_collection_items_song_id'))
        batch_op.drop_index(batch_op.f('ix_song_collection_items_collection_id'))

    op.drop_table('song_collection_items')
    with op.batch_alter_table('song_collections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_song_collections_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_song_collections_band_id'))

    op.drop_table('song_collections')
    # ### end Alembic commands ###
