"""setlists y setlist_items (Fase 5)

Revision ID: 3684ab6335e8
Revises: 147a6a78da86
Create Date: 2026-06-15 06:22:00.376245
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# identificadores de revisión, usados por Alembic.
revision: str = '3684ab6335e8'
down_revision: Union[str, None] = '147a6a78da86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('setlists',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('setlists', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_setlists_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_setlists_owner_id'), ['owner_id'], unique=False)

    op.create_table('setlist_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('setlist_id', sa.String(length=36), nullable=False),
    sa.Column('song_id', sa.String(length=36), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['setlist_id'], ['setlists.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['song_id'], ['songs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('setlist_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_setlist_items_setlist_id'), ['setlist_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_setlist_items_song_id'), ['song_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('setlist_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_setlist_items_song_id'))
        batch_op.drop_index(batch_op.f('ix_setlist_items_setlist_id'))

    op.drop_table('setlist_items')
    with op.batch_alter_table('setlists', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_setlists_owner_id'))
        batch_op.drop_index(batch_op.f('ix_setlists_deleted_at'))

    op.drop_table('setlists')
    # ### end Alembic commands ###
