"""song_collections personal: owner_id + band_id nullable

Revision ID: b6434fe1096d
Revises: 91d60406fb92
Create Date: 2026-06-24 02:12:46.242633
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# identificadores de revisión, usados por Alembic.
revision: str = 'b6434fe1096d'
down_revision: Union[str, None] = '91d60406fb92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('song_collections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_id', sa.String(length=36), nullable=True))
        batch_op.alter_column('band_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_song_collections_owner_id'), ['owner_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('song_collections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_song_collections_owner_id'))
        batch_op.alter_column('band_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
        batch_op.drop_column('owner_id')

    # ### end Alembic commands ###
