"""band cover_url (T-V5-06 identidad)

Revision ID: 37fb00af7e5c
Revises: 6323c5929bfc
Create Date: 2026-07-03 08:37:03.179873
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# identificadores de revisión, usados por Alembic.
revision: str = '37fb00af7e5c'
down_revision: Union[str, None] = '6323c5929bfc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bands', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cover_url', sa.String(length=512), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bands', schema=None) as batch_op:
        batch_op.drop_column('cover_url')

    # ### end Alembic commands ###
