"""booking fields en events (T-115)

Revision ID: c341c9bbb0ba
Revises: 5481a965f5fb
Create Date: 2026-06-21 05:35:50.085774
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# identificadores de revisión, usados por Alembic.
revision: str = 'c341c9bbb0ba'
down_revision: Union[str, None] = '5481a965f5fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contact_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('contact_phone', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('fee', sa.Numeric(precision=10, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_column('fee')
        batch_op.drop_column('contact_phone')
        batch_op.drop_column('contact_name')

    # ### end Alembic commands ###
